# Generated by Django 4.1.5 on 2023-02-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_tags_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='amount_in_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
