# Generated by Django 4.1.5 on 2023-02-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='charge_id',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sameAsShipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='ZAR', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[(1, 'Yoco'), (2, 'Stripe')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('ZA', 'South Africa')], default='ZA', max_length=100),
        ),
    ]
