# Generated by Django 4.1 on 2022-08-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_address_email_address_name_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
